### ISSUE TITLE
Java just fails on sandbox with internal NPE in GCE travis

### ISSUE THREAD

**Issue by jamox** [testmycode/tmc-sandbox#20]
```
sudo ./run-test-exercise.sh
1+0 records in
1+0 records out
20971520 bytes (21 MB) copied, 0.0289345 s, 725 MB/s
Core dump limits :
	soft - 0
	hard - NONE
Checking that ptrace can change system call numbers...OK
Checking syscall emulation patch for ptrace...OK
Checking advanced syscall emulation patch for ptrace...OK
Checking for tmpfs mount on /dev/shm.../run/shm...OK
Checking PROT_EXEC mmap in /dev/shm/...OK
Checking for the skas3 patch in the host:
  - /proc/mm...not found: No such file or directory
  - PTRACE_FAULTINFO...not found
  - PTRACE_LDT...not found
UML running in SKAS0 mode
Adding 2240512 bytes to physical memory to account for exec-shield gap
Linux version 3.11.10 (root@sandbox02.testmycode.net) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) ) #1 Sun Oct 25 14:32:49 UTC 2015
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 24779
Kernel command line: initrd=output/initrd.img ubdarc=output/rootfs.squashfs ubdbr=tmp/test-exercise.tar ubdc=tmp/output.tar mem=96M root=98:0
PID hash table entries: 512 (order: 0, 4096 bytes)
Dentry cache hash table entries: 16384 (order: 5, 131072 bytes)
Inode-cache hash table entries: 8192 (order: 4, 65536 bytes)
Sorting __ex_table...
Memory: 91108K/100492K available (2100K kernel code, 188K rwdata, 1040K rodata, 97K init, 137K bss, 9384K reserved)
NR_IRQS:15
Calibrating delay loop... 4434.32 BogoMIPS (lpj=22171648)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 256
Checking that host ptys support output SIGIO...Yes
Checking that host ptys support SIGIO on close...No, enabling workaround
Using 2.6 host AIO
NET: Registered protocol family 16
bio: create slab <bio-0> at 0
Switched to clocksource itimer
NET: Registered protocol family 2
TCP established hash table entries: 1024 (order: 2, 16384 bytes)
TCP bind hash table entries: 1024 (order: 1, 8192 bytes)
TCP: Hash tables configured (established 1024 bind 1024)
TCP: reno registered
UDP hash table entries: 256 (order: 1, 8192 bytes)
UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
NET: Registered protocol family 1
Unpacking initramfs...
Freeing initrd memory: 584K (0000000060d59000 - 0000000060deb000)
squashfs: version 4.0 (2009/01/31) Phillip Lougher
aufs 3.11-20141208
msgmni has been set to 179
io scheduler noop registered
io scheduler deadline registered
io scheduler cfq registered (default)
loop: module loaded
TCP: cubic registered
NET: Registered protocol family 17
Initialized stdio console driver
Console initialized on /dev/tty0
console [tty0] enabled
Initializing software serial port version 1
Not locking "output/rootfs.squashfs" on the host
 ubda: unknown partition table
 ubdb: unknown partition table
 ubdc: unknown partition table
TMC customized initrd starting
Not locking "output/rootfs.squashfs" on the host
SQUASHFS error: Xattrs in filesystem, these will be ignored
SQUASHFS error: unable to read xattr id index table
aufs test_add:305:mount[255]: uid/gid/perm /ro 0/0/0755, 0/0/01777
Entering tmc-init
Starting tmc-run
An exception has occurred in the compiler (1.8.0_11). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.NullPointerException
	at com.sun.tools.javac.file.ZipFileIndexArchive$ZipFileIndexFileObject.<init>(ZipFileIndexArchive.java:121)
	at com.sun.tools.javac.file.ZipFileIndexArchive.getFileObject(ZipFileIndexArchive.java:76)
	at com.sun.tools.javac.file.JavacFileManager.listArchive(JavacFileManager.java:308)
	at com.sun.tools.javac.file.JavacFileManager.listContainer(JavacFileManager.java:355)
	at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:624)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2732)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2428)
	at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
	at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:244)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:560)
	at com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:845)
	at com.sun.tools.javac.comp.MemberEnter.importAll(MemberEnter.java:154)
	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:523)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:435)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:560)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1024)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:497)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:475)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:985)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)
An exception has occurred in the compiler (1.8.0_11). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.NullPointerException
	at com.sun.tools.javac.file.ZipFileIndexArchive$ZipFileIndexFileObject.<init>(ZipFileIndexArchive.java:121)
	at com.sun.tools.javac.file.ZipFileIndexArchive.getFileObject(ZipFileIndexArchive.java:76)
	at com.sun.tools.javac.file.JavacFileManager.listArchive(JavacFileManager.java:308)
	at com.sun.tools.javac.file.JavacFileManager.listContainer(JavacFileManager.java:355)
	at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:624)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2732)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2428)
	at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
	at com.sun.vac.jvm.ClassReader$1.complete(ClassReader.java:244)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:560)
	at com.sun.tools.javac.code.Symbol$PackageSymbol.members(Symbol.java:845)
	at com.sun.tools.javac.comp.MemberEnter.importAll(Membeava:154)
	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:523)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:435)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:560)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1024)
	at com.sun.tools.javac.comp.Enter.complete(va:497)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:475)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:985)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)
Completed tmc-run. Exit code: 0
Shutting down...
reboot: System halted
```

**Comment by jamox** [comment]
We've seen this a few times but haven't really ever documented how this has been fixed.
This time the exception occurred while migrating from the legacy travis to GCE travis. 
We used same prebuilt sandbox container, but it also appears when building sandbox in travis GCE container...

I'll start of by updating java to the latest one.

**Comment by mpartel** [comment]
"SQUASHFS error: unable to read xattr id index table" suggests to me that the rootfs image might be corrupted/truncated.

**Comment by jamox** [comment]
Dunno, but this might be relevant: https://bugs.openjdk.java.net/browse/JDK-8081647

**Comment by jamox** [comment]
The `SQUASHFS error: unable to read xattr id index table` seems to be solved by setting `CONFIG_SQUASHFS_XATTR=y` while compiling the uml kernel.
